services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    environment:
      BOT_TOKEN:
      DB_URL: jdbc:postgresql://db:5432/when
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: when
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local